name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-cli:
    name: Build CLI (Go)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Build CLI
        run: |
          cd cli
          go build -v -o cdev

      - name: Run basic tests (build only for now)
        run: |
          cd cli
          go vet ./...
          go fmt ./... | tee /dev/stderr
